config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations' }

  resources :dishes do
    resources :menu_items

    member do
      post 'clone', to: 'dishes#clone'
    end
  end

  get '/menu', to: 'menu_items#index'
  get '*path', to: redirect('/menu')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dish.rb
class Dish < ApplicationRecord
  belongs_to :user
  has_many :menu_items, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  scope :personal, -> { where(public: false) }
  scope :published, -> { where(public: true) }
  scope :own, ->(user) { where(user_id: user.id) }
  scope :published_or_own, ->(user) { published.or(own(user)) }
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :user
  belongs_to :dish
  validates :day, :meal, presence: true

  DAYS = %w[monday tuesday wednesday thursday friday saturday sunday].freeze
  MEALS = %w[breakfast brunch lunch snack dinner supper].freeze
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:google]

  validates :nick, presence: true

  def self.from_omniauth(access_token)
    data = access_token.info
    email = data['email']
    user = User.find_by(email: email)
    unless user
      password = Devise.friendly_token[0, 20]
      user = User.create(nick: data['name'], email: email, password: password,
                         password_confirmation: password, provider: access_token.provider)
    end
    user
  end

  has_many :dishes, dependent: :destroy
  has_many :menu_items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_visible_dishes, only: %i[show index clone]
  before_action :set_avaiable_dishes, only: %i[edit update destroy]
  before_action :fetch_dish, only: %i[show clone]

  def new
    @dish = Dish.new
  end

  def create
    @dish = current_user.dishes.new(check_params)

    if @dish.save
      redirect_to dish_path(@dish), notice: 'Dish has been added'
    else
      flash.now[:alert] = @dish.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def edit; end

  def update
    if @dish.update(check_params)
      redirect_to dish_path, notice: 'Dish has been changed'
    else
      flash.now[:alert] = @dish.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def show; end

  def index
    @search = @dishes.ransack(params[:q])
    @dishes = @search.result
  end

  def destroy
    @dish.destroy
    redirect_to dishes_path
  end

  def clone
    @dish = Dish.new(
      user: current_user,
      name: "#{@dish.name} of #{current_user.nick}",
      details: @dish.details,
      public: false
    )
    if @dish.save
      redirect_to dish_path(@dish), notice: 'Dish has been cloned'
    else
      flash.now[:alert] = @dish.errors.full_messages.to_sentence
      render 'show'
    end
  end

  private

  def check_params
    params.require(:dish).permit(:name, :details, :public)
  end

  def set_visible_dishes
    @dishes = Dish.published_or_own(current_user).all
  end

  def set_avaiable_dishes
    @dish = Dish.own(current_user).find(params[:id])
  end

  def fetch_dish
    @dish = @dishes.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/menu_items_controller.rb
class MenuItemsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_avaiable_dish, only: %i[new create edit update]
  before_action :fetch_days_and_meals, except: :destroy
  before_action :fetch_menu_item, only: %i[destroy edit update]

  def new
    @menu_item = MenuItem.new
  end

  def create
    @menu_item = current_user.menu_items.new(check_params)
    @menu_item.dish = @dish
    if @menu_item.save
      redirect_to menu_path,
                  notice: 'Dish has been added to Menu'
    else
      flash.now[:alert] = "Ooops, sth's gone wrong"
      render 'new'
    end
  end

  def index
    @menu_items = MenuItem.where(user: current_user)
    @grouped_menu_items = MenuItem.all.includes(:dish).group_by { |item| [item.day, item.meal] }
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: 'menu',
               orientation: 'Landscape',
               layout: 'pdf.html',
               lowquality: true,
               zoom: 1,
               dpi: 72,
               encoding: 'utf8'
      end
    end
  end

  def destroy
    @menu_item.destroy
    redirect_to menu_path
  end

  def edit; end

  def update
    if @menu_item.update(check_params)
      redirect_to menu_path,
                  notice: 'Dish has been moved in Menu'
    else
      flash.now[:alert] = "Ooops, sth's gone wrong"
      render 'new'
    end
  end

  private

  def check_params
    params.require(:menu_item).permit(:day, :meal)
  end

  def fetch_days_and_meals
    @days = MenuItem::DAYS
    @meals = MenuItem::MEALS
  end

  def set_avaiable_dish
    @dish = Dish.own(current_user).find(params[:dish_id])
  end

  def fetch_menu_item
    @menu_item = MenuItem.find(params[:id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    req = request.env['omniauth.auth']
    @user = User.from_omniauth(req)
    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = req
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:nick, :email, :password,
                                 :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:nick, :email, :password,
                                 :password_confirmation, :current_password)
  end

  def update_resource(resource, params)
    if resource.provider == 'google'
      params.delete('current_password')
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.haml
%header.nav.navbar.navbar-dark.bg-menu.navbar-expand-md
  %button.navbar-toggler{'data-target': '#mainmenu', 'data-toggle': 'collapse', type: 'button'}
    %span.navbar-toggler-icon
  #mainmenu.collapse.navbar-collapse
    %ul.navbar-nav
      - if user_signed_in?
        %li.nav-item
          .nav-link
            = link_to 'New dish', new_dish_path
        %li.nav-item
          .nav-link
            = link_to 'All dishes', dishes_path
        %li.nav-item
          .nav-link
            = link_to 'Menu', menu_path
        %li.nav-item
          .nav-link
            = link_to 'Menu PDF', menu_path(format: :pdf), target: :_blank
        %li.nav-item.dropdown
          .nav-link.dropdown-toggle{'data-toggle': 'dropdown'} #{current_user.nick}
          .dropdown-menu.bg-menu
            .dropdown-item
              = link_to 'Delete account', user_registration_path, method: :delete
            .dropdown-item
              = link_to 'Edit account', edit_user_registration_path
            .dropdown-item
              = link_to 'Log out', destroy_user_session_path, method: :delete
      - else
        %li.nav-item
          .nav-link
            = link_to 'Sign up', new_user_registration_path
        %li.nav-item
          .nav-link
            = link_to 'Login', new_user_session_path

app/views/dishes/_dish_form.html.haml
= form_for [@dish] do |dish|
  %h4= dish.label :name
  %h4= dish.text_field :name
  %h4= dish.label :details
  %h4= dish.text_area :details
  %h4= dish.label :public
  %h4= dish.check_box :public
  = dish.submit 'Submit'
  = link_to "Cancel", dishes_path

app/views/dishes/edit.html.haml
%body.element-bg
  .container
    .row
      .col-md-7
      .col-md-5
        %h2 Edit Dish:
        .element
          = render "dish_form"

app/views/dishes/index.html.haml
%body.index-bg
  .container
    .row.justify-content-center.align-items-center
      .index
        = search_form_for @search do |f|
          = f.label :name_cont, 'name of dish contains'
          = f.search_field :name_cont

        = search_form_for @search do |f|
          = f.label :user_nick_cont, "user's nick contains"
          = f.search_field :user_nick_cont

        %table{cellpadding: "7"}
          %tr.heading
            %td= sort_link(@search, :name, 'name of dish')
            %td= sort_link(@search, :created_at, 'created at')
            %td= sort_link(@search, :user_nick, "user's nick")

          - @dishes.each do |dish|
            %tr
              %td= link_to "#{dish.name}", dish_path(dish)
              %td= dish.created_at.strftime('%Y-%m-%d')
              %td= dish.user.nick

app/views/dishes/new.html.haml
%body.element-bg
  .container
    .row
      .col-md-7
      .col-md-4
        %h2 New Dish:
        .element
          = render "dish_form"

app/views/dishes/show.html.haml
%body.element-bg
  .container
    .row
      .col-md-7
      .col-md-4
        %h2= @dish.name
        .element
          %h4 added by #{@dish.user.nick}
          - if @dish.details.present?
            %h4= @dish.details
          = link_to 'Clone', clone_dish_path, method: :post
          - if @dish.user == current_user
            = link_to 'Edit dish', edit_dish_path
            = link_to 'Delete dish', dish_path, method: :delete
            = link_to 'Add to MENU', new_dish_menu_item_path(@dish)

app/views/home/index.html.haml
%body.home-bg

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HealthyMenu
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'header'
    = yield
    %p.notice= notice
    %p.alert= alert

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PDFs - Ruby on Rails</title>
  <%= wicked_pdf_stylesheet_link_tag "menu" %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/menu_items/_menu_item_form.html.haml
%h3 @dish.name
= form_for [@dish, @menu_item] do |menu_item|
  %h4= menu_item.label :day
  %h4= menu_item.select :day, options_for_select(@days)
  %h4= menu_item.label :meal
  %h4= menu_item.select :meal, options_for_select(@meals)
  = menu_item.submit 'Submit'
  = link_to "Cancel", menu_path

app/views/menu_items/edit.html.haml
%body.element-bg
  .container
    .row
      .col-md-7
      .col-md-4
        %h2 Change menu:
        .element
          = render "menu_item_form"

app/views/menu_items/index.html.haml
%body.index-bg
  .container-fluid
    .menu-box
      %table{:cellpadding => "0", :cellspacing => "0"}
        %tr.heading
          %td
          - @days.each do |day|
            %td= day.humanize
        - @meals.each do |meal|
          %tr
            %td= meal
            - @days.each do |day|
              %td
                - if @grouped_menu_items[[day, meal]]
                  - @grouped_menu_items[[day, meal]].each do |menu_item|
                    = link_to "#{menu_item.dish.name}", dish_path(menu_item.dish.id)
                    = link_to 'E', edit_dish_menu_item_path(menu_item.dish.id, menu_item)
                    = link_to 'D', dish_menu_item_path(menu_item.dish.id, menu_item), method: :delete                                       |

app/views/menu_items/index.pdf.haml
.menu-box
  %table{:cellpadding => "0", :cellspacing => "0"}
    %tr.heading
      %td
      - @days.each do |day|
        %td= day.humanize
    - @meals.each do |meal|
      %tr
        %td= meal
        - @days.each do |day|
          %td
            - if @grouped_menu_items[[day, meal]]
              - @grouped_menu_items[[day, meal]].each do |menu_item|
                = menu_item.dish.name

app/views/menu_items/new.html.haml
%body.element-bg
  .container
    .row
      .col-md-7
      .col-md-4
        %h2 Add dish to menu:
        .element
          = render "menu_item_form"